### ISSUE TITLE
Which languages are supported?

### ISSUE THREAD

**Issue by DiTo97** [davidlenz/pvtm#15]
Hi, as the title suggests, I would like to know which languages are supported by your model. I saw that your package builds upon [spaCy](https://spacy.io/); thus, I imagined that it would work with any language, granted that the correct spaCy language model was provided. But, a few of your functions (i.e., ``lemmatization``) check only for English and German in the ``lang`` arg.

I hope you can clarify it a bit.

By the way, I would like to apply your model to a custom corpora of Italian transcripts. If it's not supported at the moment, I may even consider submitting a pull request for it, if you give me a few hints on how to modify your package to allow for the Italian language, as well.

**Comment by davidlenz** [comment]
Hey @DiTo97 , thanks for your interest in the package. I havent really come around to fix those smaller issues after the initial implementation for the paper.
I think you should be just fine with adding a line for italian [around here](https://github.com/davidlenz/pvtm/blob/5752bc8ecacca5909e9655813e6b858bcaecec28/pvtm/pvtm.py#L142) since the language shouldnt matter outside the lemmatization procedure. Also please feel free to pr, would happily accept.
